# Generated by Django 2.1.5 on 2019-11-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191105_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcategory',
            name='category_image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
