# Generated by Django 2.1.5 on 2019-11-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tutorialcategory_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialcategory',
            name='category_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
