# Generated by Django 2.1.5 on 2019-11-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191107_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialcategory',
            name='category_image',
        ),
        migrations.AddField(
            model_name='tutorialcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
