# Generated by Django 2.2.7 on 2019-11-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='tutorialcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
