# Generated by Django 2.2.7 on 2019-11-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_tutorialcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
